### NumPy Tutorial

In [3]:
import numpy as np

In [9]:
A = np.linspace(0, 10, 100+1)

In [11]:
len(A)
A

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [7]:
A = np.linspace(0, 10, 100)

In [8]:
len(A)

100

In [12]:
np.info('ufunc')

     *** Found in numpy ***
 ufunc()

Functions that operate element by element on whole arrays.

To see the documentation for a specific ufunc, use `info`.  For
example, ``np.info(np.sin)``.  Because ufuncs are written in C
(for speed) and linked into Python with NumPy's ufunc facility,
Python's help() function finds this page whenever help() is called
on a ufunc.

A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.

Calling ufuncs:

op(*x[, out], where=True, **kwargs)
Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.

The broadcasting rules are:

* Dimensions of length 1 may be prepended to either array.
* Arrays may be repeated along dimensions of length 1.

Parameters
----------
*x : array_like
    Input arrays.
out : ndarray, None, or tuple of ndarray and None, optional
    Alternate array object(s) in which to put the result; if provided, it
    must have a shape that the inputs broadcast to. A tuple of arrays
    (possible only as

In [13]:
A = np.array([1, 2, 3, 4])

In [14]:
A + 2

array([3, 4, 5, 6])

In [15]:
2 + A

array([3, 4, 5, 6])

In [16]:
2**A

array([ 2,  4,  8, 16])

In [17]:
2**np.array(range(20))

array([     1,      2,      4,      8,     16,     32,     64,    128,
          256,    512,   1024,   2048,   4096,   8192,  16384,  32768,
        65536, 131072, 262144, 524288])

In [18]:
A < 5

array([ True,  True,  True,  True])

In [19]:
A < 2

array([ True, False, False, False])

In [20]:
A[(A < 50) & (A % 2 == 0)] = 222 

In [21]:
A

array([  1, 222,   3, 222])